### ISSUE TITLE
*** FRU__delta_init(): Attempt to start when running!

### ISSUE THREAD

**Issue by luo-wang** [Jashcraf/poke#110]
When I am running code using PyCharm or Spyder, this line of text appears on the console and I don't know how to solve it.
The text is "*** FRU__delta_init(): Attempt to start when running!"
![微信截图_20240909165528](https://github.com/user-attachments/assets/de0e97d2-feb4-4d1b-8d3d-18268093f2e5)

**Comment by Jashcraf** [comment]
Oh interesting I haven't seen this before.

What version of Zemax / CODE V are you using?

**Comment by luo-wang** [comment]
这是来自QQ邮箱的自动回复邮件。你好，我已收到你的来信！
