### ISSUE TITLE
6.4 Compare GBD against other design codes

### ISSUE THREAD

**Issue by Jashcraf** [Jashcraf/poke#29]
## Simulation Parameters

|     **Specification**    | **Value** |
|:------------------------:|:---------:|
|        wavelength        |   1.65um  |
|           npix           |    256    |
|        pixelscale        | 3.90625um |
| beamlets across aperture |    101    |
| output units |    irradiance   |

## Optical System is the HST
<img width="572" alt="image" src="https://user-images.githubusercontent.com/25557892/188485556-23d72b58-8ab3-4788-8460-4e29f19edb24.png">

## Experiment

I'd like to use various optical modeling codes with coherent capabilities in order to determine how well the PSF is reconstructed. Ideally this simulation is done both with and without the Hubble aperture obscuration.

- [x] Poke/GBD
- [ ] POPPY Fresnel w/ Zemax wavefront
- [x] Zemax Huygens PSF
- [ ] CODE V Beam Synthesis Propagation
- [ ] FRED Coherent Analysis

**Comment by trentjbrendel** [comment]
@Jashcraf, could you clarify the details of the beam you want me to inject into the optical system? Each of these codes handles this slightly differently and I want to make sure I'm simulating the right thing. Thanks!

**Comment by Jashcraf** [comment]
Sure - I'm looking for a collimated beam from infinity on-axis, so a truncated plane wave with 0 field value w.r.t. the optical axis.

If I recall, they both accept some parameters to constrain the beamlet calculation. I think FRED gives the user more control than CODE V does, so if "overlap factor" or something similar is available, set it to 1.7.

Also (and I'll add to the list above), that these should be **Irradiance** calculations. Intensity is also fine, just need the units to be Power instead of field. The phase doesn't matter so much here.

@trentjbrendel does that clarify it a bit better?

**Comment by Jashcraf** [comment]
Oh also @trentjbrendel we should synch up on the right aperture to use, so just simulate the unobscured circular entrance pupil for now.

**Comment by Jashcraf** [comment]
Top is GBD v.s. Analytical Airy, bottom is Zemax Huygens v.s. Analytical Airy
<img width="735" alt="image" src="https://user-images.githubusercontent.com/25557892/189201831-89edeca6-2b58-4f77-ba12-48d9375d2f12.png">

**Comment by Jashcraf** [comment]
@trentjbrendel thoughts on this figure? Need to add titles but anything else?

**Comment by trentjbrendel** [comment]
> 

Those figures look great! Is this the format you want me to use for reporting my results?

**Comment by Jashcraf** [comment]
Nah I just need the raw data from you, frequently the centering of different diffraction methods is not the same so sometimes I need to shift things around. Also here's some titles.
![image](https://user-images.githubusercontent.com/25557892/189530605-bcf8de08-ec4b-4502-86de-92895e15d5b6.png)
