### ISSUE TITLE
Debugging Inconsistent field on translation

### ISSUE THREAD

**Issue by Jashcraf** [Jashcraf/poke#54]
r_ray and k_ray look good to me, let's try the ray transfer matrices.

# A matrix
![image](https://user-images.githubusercontent.com/25557892/229977594-f90ca8c3-3aa4-4d2a-b400-fdb27091a790.png)

# B Matrix
![image](https://user-images.githubusercontent.com/25557892/229977645-5fb86fbf-7d05-4e54-a7c8-a1ecd575ded2.png)

# C matrix
![image](https://user-images.githubusercontent.com/25557892/229977694-d9ae5055-74d3-4e9d-8bb1-288372a51ebf.png)

# D matrix
![image](https://user-images.githubusercontent.com/25557892/229977729-8894d5e0-bb0c-4c4f-804b-1617640b1af9.png)

**Comment by Jashcraf** [comment]
top is new algo, bottom is old

overall the new one looks less regular, maybe an operation got broadcast over an unintended dimesnion

**Comment by Jashcraf** [comment]
Delta calculation
![image](https://user-images.githubusercontent.com/25557892/229978366-b3c9a64e-a1d5-424d-8486-66c9a96adc41.png)

These actually just look like the right values in perhaps different places. Specifically - the middle two columns are switched

**Comment by Jashcraf** [comment]
# K rays before delta calculation are the same, but different order
![image](https://user-images.githubusercontent.com/25557892/230138733-f1014eed-4ea7-4e9f-853c-1644dbb9d1c6.png)

**Comment by Jashcraf** [comment]
Oh my god lData and mData were flipped in the function inputs

**Comment by Jashcraf** [comment]
Delta is good (left gbd, right beamlets)
![image](https://user-images.githubusercontent.com/25557892/230140894-9a8aac92-6981-4fc6-b16a-b525403bb4b4.png)

**Comment by Jashcraf** [comment]
# After orthogonal transformation
k_rays on both == np.array([0,0,1]), which is good!
r_rays look a little different at first glance, can we use fewer beamlets without breaking?

![image](https://user-images.githubusercontent.com/25557892/230142069-2ec33956-0715-4238-9d24-9d00fde87da5.png)

**Comment by Jashcraf** [comment]
Gonna look at the +X differential ray, r_rays should basically all be at x,y = 0 here.
They are different and transposed!
![image](https://user-images.githubusercontent.com/25557892/230144262-8730f208-83b4-4fa3-b725-b1cdaba4a1af.png)

**Comment by Jashcraf** [comment]
Ah I think I might have been looking at the wrong coordinate
here is the x,y,z position for each ray at a given pixel - which it is constant across
![image](https://user-images.githubusercontent.com/25557892/230150331-29c340a4-5e25-46a1-8a1a-a96302ba131d.png)
consistency!

**Comment by Jashcraf** [comment]
plotting after the delta propagation, the beamlets array is entirely black?
![image](https://user-images.githubusercontent.com/25557892/230150747-bb892d69-9495-4ab2-ad6c-0383991d0cd3.png)

**Comment by Jashcraf** [comment]
Oh it's because I'm passing it weird data, the rayset index is now in the first when it should be in the zeroth. 
consistency!
![image](https://user-images.githubusercontent.com/25557892/230151776-25adf2f4-b485-40ae-b601-5c8a9ba72bc1.png)

**Comment by Jashcraf** [comment]
Checking after orthogonal transformation. Might have some nan vals in the old method. Viridis is r_data and magma is k_data
![image](https://user-images.githubusercontent.com/25557892/230153368-edb3486e-1f55-46a9-a14a-3e331e93d453.png)
![image](https://user-images.githubusercontent.com/25557892/230153476-04b41cba-8f93-43f6-a84d-8ff272646ed4.png)

Both look good (save the nans)

**Comment by Jashcraf** [comment]
# Axx
![image](https://user-images.githubusercontent.com/25557892/230154461-0195cd2a-0ee6-4cde-93d4-fe657b98235d.png)

# Cxx - looks wrong
![image](https://user-images.githubusercontent.com/25557892/230154697-46f0f192-00c5-4ca4-aa4b-501aab8d9d6e.png)

# Bxx - looks wrong, values of near 50 are about what we'd expect given the HST focal length
![image](https://user-images.githubusercontent.com/25557892/230154777-4b8b811a-2206-4e7d-b4bd-3f27d89cacf7.png)

# Dxx - also doesn't look spectacular
![image](https://user-images.githubusercontent.com/25557892/230154965-575706cc-d207-4921-92b7-b53b0cff7007.png)

**Comment by Jashcraf** [comment]
Ah I forgot to normalize the l vector in the orthogonal transfer matrix

# Axx - looking good!
![image](https://user-images.githubusercontent.com/25557892/230162540-c938b7b9-7e2c-43ce-8309-55f1bbc306fd.png)
# Cxx - looking good!
![image](https://user-images.githubusercontent.com/25557892/230162702-8161efe7-f80e-4526-bf78-9767dc665513.png)
# Bxx - looking good!
![image](https://user-images.githubusercontent.com/25557892/230162790-1dfeb092-809c-41de-a1fb-91a9327aea49.png)
# Dxx - tell me why im so excited
![image](https://user-images.githubusercontent.com/25557892/230162875-f283f527-21c4-4937-94b3-260fb6b8e047.png)

**Comment by Jashcraf** [comment]
WE WIN
![image](https://user-images.githubusercontent.com/25557892/230164223-960b99f8-6476-4b60-a3ca-9346e1905a9c.png)

time to try the misaligned case

**Comment by Jashcraf** [comment]
Breaks during misalignment and focus - I suspect that this has to do with where the ray positions are
![image](https://user-images.githubusercontent.com/25557892/230165487-f00ce01c-8eeb-4117-ad57-96801d5533fa.png)

**Comment by Jashcraf** [comment]
![image](https://user-images.githubusercontent.com/25557892/230181709-4264615a-d747-4a14-b5d7-481edeb247bf.png)

Nah the ray positions are identical

**Comment by Jashcraf** [comment]
Let's check the final ingredients for the matrix, starting with Amplitude
# |Amplitude|
![image](https://user-images.githubusercontent.com/25557892/230182971-55769d84-0e49-43f8-9af2-cc02cf77ea75.png)
Looks slightly different, don't know what this could be from (other than the complex beam parameter computation)

# Angle{Phase}
This is very different!
![image](https://user-images.githubusercontent.com/25557892/230183247-b521a28d-66ac-402f-85f5-77cc37ae3e0d.png)

(The vertical lines are the new algorithm)

**Comment by Jashcraf** [comment]
For the misaligned case the ray transfer matrices are different!
# Axx (left is beamlets right is gbd)
![image](https://user-images.githubusercontent.com/25557892/230187050-bab76ade-ea8f-4f68-888b-edb9cb5a598a.png)

**Comment by Jashcraf** [comment]
Works for the defocused case
![image](https://user-images.githubusercontent.com/25557892/230189818-8041ff8c-1658-44b7-9c7d-e79b67c7a574.png)

**Comment by Jashcraf** [comment]
The orthogonal transformation matrix is looking good, each image is a row in the matrix
![image](https://user-images.githubusercontent.com/25557892/230192257-43bde3de-0633-4f9a-afe8-27e8aae33920.png)
![image](https://user-images.githubusercontent.com/25557892/230194146-2f767bfc-7679-430e-b7bb-2ad079d41b94.png)
![image](https://user-images.githubusercontent.com/25557892/230194687-66a9adcd-eec4-4c2f-9b8d-95a26cf51a5a.png)

**Comment by Jashcraf** [comment]
![image](https://user-images.githubusercontent.com/25557892/230200091-2d78d8c5-52a2-40b2-89e1-b03a55a1bdff.png)
The detector coords are wrong!

**Comment by Jashcraf** [comment]
![image](https://user-images.githubusercontent.com/25557892/230206326-6767b81f-bcec-4e2c-b1bc-aa48e4ae826f.png)
turns out you need to provide the offset to the rays, not detector

**Comment by trentjbrendel** [comment]
This is fascinating. Thanks for sharing, Jaren!
